// ----------------------------------
// /!\ Generated code. Do not modify.
// ----------------------------------
@file:Suppress("TopLevelPropertyNaming", "TrailingWhitespace", "MaxLineLength")

package com.gabrieldrn.carbon.foundation.color.syntax

import androidx.compose.ui.graphics.Color
import kotlin.Suppress

/**
 * Color tokens for the Syntax component in the Gray90 theme.
 */
public val Gray90SyntaxColors: SyntaxColors = 
    SyntaxColors(
        syntaxAngleBracket = Color(0xFF8D8D8D),
        syntaxAnnotation = Color(0xFF08BDBA),
        syntaxArithmeticOperator = Color(0xFFE0E0E0),
        syntaxAtom = Color(0xFFF4F4F4),
        syntaxAttribute = Color(0xFF33B1FF),
        syntaxAttributeName = Color(0xFF33B1FF),
        syntaxAttributeValue = Color(0xFFF4F4F4),
        syntaxBitwiseOperator = Color(0xFFE0E0E0),
        syntaxBlockComment = Color(0xFF42BE65),
        syntaxBool = Color(0xFFF4F4F4),
        syntaxBrace = Color(0xFFE0E0E0),
        syntaxBracket = Color(0xFFE0E0E0),
        syntaxCharacter = Color(0xFFF4F4F4),
        syntaxClassName = Color(0xFF3DDBD9),
        syntaxColor = Color(0xFFF4F4F4),
        syntaxComment = Color(0xFF42BE65),
        syntaxCompareOperator = Color(0xFFE0E0E0),
        syntaxConstant = Color(0xFF4589FF),
        syntaxContent = Color(0xFFF4F4F4),
        syntaxContentSeparator = Color(0xFFE0E0E0),
        syntaxControlKeyword = Color(0xFFBE95FF),
        syntaxControlOperator = Color(0xFFBE95FF),
        syntaxDefinition = Color(0xFF33B1FF),
        syntaxDefinitionKeyword = Color(0xFF33B1FF),
        syntaxDefinitionOperator = Color(0xFF33B1FF),
        syntaxDeleted = Color(0xFFA2191F),
        syntaxDerefOperator = Color(0xFFE0E0E0),
        syntaxDocComment = Color(0xFF42BE65),
        syntaxDocString = Color(0xFFF4F4F4),
        syntaxDocumentMeta = Color(0xFF42BE65),
        syntaxEmphasis = Color(0xFFF4F4F4),
        syntaxEscape = Color(0xFFE0E0E0),
        syntaxFloat = Color(0xFF6FDC8C),
        syntaxFunction = Color(0xFFF1C21B),
        syntaxHeading = Color(0xFF33B1FF),
        syntaxHeading1 = Color(0xFF33B1FF),
        syntaxHeading2 = Color(0xFF33B1FF),
        syntaxHeading3 = Color(0xFF33B1FF),
        syntaxHeading4 = Color(0xFF33B1FF),
        syntaxHeading5 = Color(0xFF33B1FF),
        syntaxHeading6 = Color(0xFF33B1FF),
        syntaxInserted = Color(0xFF198038),
        syntaxInteger = Color(0xFF6FDC8C),
        syntaxInvalid = Color(0xFFFA4D56),
        syntaxKeyword = Color(0xFF4589FF),
        syntaxLabelName = Color(0xFFA6C8FF),
        syntaxLineComment = Color(0xFF42BE65),
        syntaxLink = Color(0xFF4589FF),
        syntaxList = Color(0xFFF4F4F4),
        syntaxLiteral = Color(0xFFF4F4F4),
        syntaxLocal = Color(0xFFA6C8FF),
        syntaxLogicOperator = Color(0xFFE0E0E0),
        syntaxMacroName = Color(0xFFF4F4F4),
        syntaxMeta = Color(0xFF42BE65),
        syntaxModifier = Color(0xFF4589FF),
        syntaxModuleKeyword = Color(0xFFBE95FF),
        syntaxMonospace = Color(0xFFF4F4F4),
        syntaxName = Color(0xFFA6C8FF),
        syntaxNamespace = Color(0xFF3DDBD9),
        syntaxNull = Color(0xFFF4F4F4),
        syntaxNumber = Color(0xFF6FDC8C),
        syntaxOperator = Color(0xFFE0E0E0),
        syntaxOperatorKeyword = Color(0xFF4589FF),
        syntaxParen = Color(0xFFE0E0E0),
        syntaxProcessingInstruction = Color(0xFFF4F4F4),
        syntaxPropertyName = Color(0xFF33B1FF),
        syntaxPunctuation = Color(0xFFE0E0E0),
        syntaxQuote = Color(0xFF42BE65),
        syntaxRegexp = Color(0xFFBE95FF),
        syntaxSelf = Color(0xFF3DDBD9),
        syntaxSeparator = Color(0xFFE0E0E0),
        syntaxSpecial = Color(0xFF4589FF),
        syntaxSpecialString = Color(0xFFBE95FF),
        syntaxSquareBracket = Color(0xFFE0E0E0),
        syntaxStandard = Color(0xFF4589FF),
        syntaxStrikethrough = Color(0xFFF4F4F4),
        syntaxString = Color(0xFFF4F4F4),
        syntaxStrong = Color(0xFFF4F4F4),
        syntaxTag = Color(0xFF3DDBD9),
        syntaxTagName = Color(0xFF3DDBD9),
        syntaxType = Color(0xFF3DDBD9),
        syntaxTypeName = Color(0xFF3DDBD9),
        syntaxTypeOperator = Color(0xFF3DDBD9),
        syntaxUnit = Color(0xFF6FDC8C),
        syntaxUpdateOperator = Color(0xFFE0E0E0),
        syntaxUrl = Color(0xFFE0E0E0),
        syntaxVariable = Color(0xFFA6C8FF),
        syntaxVariableName = Color(0xFFA6C8FF)
    )
