// ----------------------------------
// /!\ Generated code. Do not modify.
// ----------------------------------
package com.gabrieldrn.carbon.foundation.color.syntax

import androidx.compose.runtime.Immutable
import androidx.compose.ui.graphics.Color
import kotlin.Suppress

/**
 * Color tokens for the Syntax component.
 */
@Immutable
@Suppress("UndocumentedPublicProperty", "MaxLineLength")
public data class SyntaxColors(
    public val syntaxAngleBracket: Color,
    public val syntaxAnnotation: Color,
    public val syntaxArithmeticOperator: Color,
    public val syntaxAtom: Color,
    public val syntaxAttribute: Color,
    public val syntaxAttributeName: Color,
    public val syntaxAttributeValue: Color,
    public val syntaxBitwiseOperator: Color,
    public val syntaxBlockComment: Color,
    public val syntaxBool: Color,
    public val syntaxBrace: Color,
    public val syntaxBracket: Color,
    public val syntaxCharacter: Color,
    public val syntaxClassName: Color,
    public val syntaxColor: Color,
    public val syntaxComment: Color,
    public val syntaxCompareOperator: Color,
    public val syntaxConstant: Color,
    public val syntaxContent: Color,
    public val syntaxContentSeparator: Color,
    public val syntaxControlKeyword: Color,
    public val syntaxControlOperator: Color,
    public val syntaxDefinition: Color,
    public val syntaxDefinitionKeyword: Color,
    public val syntaxDefinitionOperator: Color,
    public val syntaxDeleted: Color,
    public val syntaxDerefOperator: Color,
    public val syntaxDocComment: Color,
    public val syntaxDocString: Color,
    public val syntaxDocumentMeta: Color,
    public val syntaxEmphasis: Color,
    public val syntaxEscape: Color,
    public val syntaxFloat: Color,
    public val syntaxFunction: Color,
    public val syntaxHeading: Color,
    public val syntaxHeading1: Color,
    public val syntaxHeading2: Color,
    public val syntaxHeading3: Color,
    public val syntaxHeading4: Color,
    public val syntaxHeading5: Color,
    public val syntaxHeading6: Color,
    public val syntaxInserted: Color,
    public val syntaxInteger: Color,
    public val syntaxInvalid: Color,
    public val syntaxKeyword: Color,
    public val syntaxLabelName: Color,
    public val syntaxLineComment: Color,
    public val syntaxLink: Color,
    public val syntaxList: Color,
    public val syntaxLiteral: Color,
    public val syntaxLocal: Color,
    public val syntaxLogicOperator: Color,
    public val syntaxMacroName: Color,
    public val syntaxMeta: Color,
    public val syntaxModifier: Color,
    public val syntaxModuleKeyword: Color,
    public val syntaxMonospace: Color,
    public val syntaxName: Color,
    public val syntaxNamespace: Color,
    public val syntaxNull: Color,
    public val syntaxNumber: Color,
    public val syntaxOperator: Color,
    public val syntaxOperatorKeyword: Color,
    public val syntaxParen: Color,
    public val syntaxProcessingInstruction: Color,
    public val syntaxPropertyName: Color,
    public val syntaxPunctuation: Color,
    public val syntaxQuote: Color,
    public val syntaxRegexp: Color,
    public val syntaxSelf: Color,
    public val syntaxSeparator: Color,
    public val syntaxSpecial: Color,
    public val syntaxSpecialString: Color,
    public val syntaxSquareBracket: Color,
    public val syntaxStandard: Color,
    public val syntaxStrikethrough: Color,
    public val syntaxString: Color,
    public val syntaxStrong: Color,
    public val syntaxTag: Color,
    public val syntaxTagName: Color,
    public val syntaxType: Color,
    public val syntaxTypeName: Color,
    public val syntaxTypeOperator: Color,
    public val syntaxUnit: Color,
    public val syntaxUpdateOperator: Color,
    public val syntaxUrl: Color,
    public val syntaxVariable: Color,
    public val syntaxVariableName: Color,
)
